<a href="https://colab.research.google.com/github/bharath2213/Python-Tasks/blob/main/Python_Task_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a program to print the following pattern (use for loop)


        A  
        B C  
        D E F  
        G H I J  
        K L M N O  
        P Q R S T U

In [ ]:

# Initialize starting character
char = ord('A')

# Number of rows in the pattern
rows = 6

for i in range(1, rows + 1):
    for j in range(i):
        print(chr(char), end=' ')
        char += 1
    print()


A 
B C 
D E F 
G H I J 
K L M N O 
P Q R S T U 



2. Write a program to print tables from 2 to a user provided range (use for loop)

  hint: to get the user input   -   int(input('Enter the range : '))

In [ ]:
end_range = int(input('Enter the range: '))
for i in range(2, end_range + 1):
    print(f"\nTable of {i}:")
    for j in range(1, 11):
        print(f"{i} x {j} = {i * j}")


Enter the range: 5

Table of 2:
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

Table of 3:
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

Table of 4:
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

Table of 5:
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


3. Use list comprehension to find words whose length is less than 5 from the given list

  planet = ['sky', 'sun', 'moon','star','Jupiter','mars','Neptune', 'Pluto']

In [ ]:
planet = ['sky', 'sun', 'moon', 'star', 'Jupiter', 'mars', 'Neptune']
short_words = [word for word in planet if len(word) < 5]
print(short_words)


['sky', 'sun', 'moon', 'star', 'mars']


4. Write a program to append a dictionary to a tuple

  The original tuple : (4, 5, 6)

  Tuple after addition of dictionary : (4, 5, 6, {'gfg': 1, 'is': 2, 'best': 3})

In [ ]:
# Original tuple
A = (4, 5, 6)

# Dictionary to append
B = {'gfg': 1, 'is': 2, 'best': 3}

# Appending the dictionary by creating a new tuple
result_tuple =A + (B,)
print("Tuple after addition of dictionary:", result_tuple)


Tuple after addition of dictionary: (4, 5, 6, {'gfg': 1, 'is': 2, 'best': 3})


5. A list of words is given. Convert the words into uppercase (use lambda and map functions)

    lsbool = ['True','FALse','tRUe','tRue','False','faLse','True']
    
    Output: ['TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE']

In [ ]:
lsbool = ['True', 'FALse', 'tRUe', 'tRue', 'False', 'faLse', 'True']

# Convert to uppercase using map and lambda
result = list(map(lambda x: x.upper(), lsbool))
print(result)


['TRUE', 'FALSE', 'TRUE', 'TRUE', 'FALSE', 'FALSE', 'TRUE']


6. A list of words is given. Define a function to find the words from the list that have their second character in uppercase

  ls = ['hello', 'Dear', 'hOw', 'ARe', 'You']
  
  Output: ['hOw', 'ARe']

In [ ]:
def second_char_uppercase(words):
    return [word for word in words if len(word) > 1 and word[1].isupper()]

# Sample list
ls = ['hello', 'Dear', 'hOw', 'ARe', 'You']
result = second_char_uppercase(ls)
print(result)


['hOw', 'ARe']


7.Create an array of integers from 20 to 2 with a step of -2

In [ ]:
arr = list(range(20, 1, -2))
print(arr)


[20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


8.Replace all odd numbers in the array with -2

    num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [ ]:
import numpy as np
num_array = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

# Replace odd numbers with -2
num_array[num_array % 2 == 1] = -2
print(num_array)


[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


9.Stack two arrays vertically'

    quantity1 = np.arange(10).reshape(2,-1)
    quantity2 = np.repeat(1, 10).reshape(2,-1)

In [ ]:
import numpy as np

# Creating the arrays
quantity1 = np.arange(10).reshape(2, -1)
quantity2 = np.repeat(1, 10).reshape(2, -1)

# Stacking vertically
result = np.vstack((quantity1, quantity2))
print(result)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


10. Reverse each of the rows of the 2D array

    num_array1 = np.arange(16).reshape(4,4)

In [ ]:
import numpy as np

# Create the 2D array
num_array1 = np.arange(16).reshape(4, 4)

# Reverse each row
reversed_rows_array = num_array1[:, ::-1]
print(reversed_rows_array)


[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


11.  Create a dictionary named 'europe_dict' which has names of countries in europe, their capital and their population.


<table>
  <tr>
  <th>Country </th>
  <th>Capital</th>
  <th>Population</th>    
  </tr>
  <tr>
  <td>Spain</td>
  <td>Madrid</td>
  <td>46.77</td>    
  </tr>
  <tr>
  <td>France</td>
  <td>Paris</td>
  <td>66.03</td>
  </tr>
  <tr>
  <td>Germany</td>
  <td>Berlin</td>
  <td>80.62</td>
  </tr>
  <tr>
  <td>Norway</td>
  <td>Oslo</td>
  <td>5.084 </td>
</tr>
</table>

In [ ]:
# Creating the dictionary
europe_dict = {
    'Spain': {'Capital': 'Madrid', 'Population': 46.77},
    'France': {'Capital': 'Paris', 'Population': 66.03},
    'Germany': {'Capital': 'Berlin', 'Population': 80.62},
    'Norway': {'Capital': 'Oslo', 'Population': 5.084}
}
print(europe_dict)


{'Spain': {'Capital': 'Madrid', 'Population': 46.77}, 'France': {'Capital': 'Paris', 'Population': 66.03}, 'Germany': {'Capital': 'Berlin', 'Population': 80.62}, 'Norway': {'Capital': 'Oslo', 'Population': 5.084}}


 12. In the data in question 11, add a new column 'FamousFor'. The column tells what each country is famous for.

 <table>
  <tr>
  <th>Country </th>
  <th>FamousFor</th>   
  </tr>
  <tr>
  <td>Spain</td>
  <td>Football</td>  
  </tr>
  <tr>
  <td>France</td>
  <td>Eiffel Tower</td>
  </tr>
  <tr>
  <td>Germany</td>
  <td>Cars</td>
  </tr>
  <tr>
  <td>Norway</td>
  <td>Midnight sun</td>
</tr>
</table>

In [ ]:
# Updating the dictionary with the 'FamousFor' column
europe_dict = {
    'Spain': {'Capital': 'Madrid', 'Population': 46.77, 'FamousFor': 'Football'},
    'France': {'Capital': 'Paris', 'Population': 66.03, 'FamousFor': 'Eiffel Tower'},
    'Germany': {'Capital': 'Berlin', 'Population': 80.62, 'FamousFor': 'Cars'},
    'Norway': {'Capital': 'Oslo', 'Population': 5.084, 'FamousFor': 'Midnight sun'}
}
print(europe_dict)


{'Spain': {'Capital': 'Madrid', 'Population': 46.77, 'FamousFor': 'Football'}, 'France': {'Capital': 'Paris', 'Population': 66.03, 'FamousFor': 'Eiffel Tower'}, 'Germany': {'Capital': 'Berlin', 'Population': 80.62, 'FamousFor': 'Cars'}, 'Norway': {'Capital': 'Oslo', 'Population': 5.084, 'FamousFor': 'Midnight sun'}}


13. Use the data created in question 11, to do the following:

   i) Access column 'Captial' by specifying the column number.

   ii) Access column 'Population' by specifying the column name.

  iii) Access a country information


In [ ]:
# Accessing 'Capital' for each country (by column position, assuming 1st column for 'Capital')
capital_column = [info['Capital'] for info in europe_dict.values()]
print("Capital Column:", capital_column)

# Accessing 'Population' column by name
population_column = [info['Population'] for info in europe_dict.values()]
print("Population Column:", population_column)

# Accessing information for a specific country (e.g., Spain)
spain_info = europe_dict['Spain']
print("Spain Info:", spain_info)


Capital Column: ['Madrid', 'Paris', 'Berlin', 'Oslo']
Population Column: [46.77, 66.03, 80.62, 5.084]
Spain Info: {'Capital': 'Madrid', 'Population': 46.77, 'FamousFor': 'Football'}


14. check dimension/shape, data types of the dataframe create on question 11



In [ ]:
import pandas as pd

# Creating the DataFrame from europe_dict
europe_dict = {
    'Spain': {'Capital': 'Madrid', 'Population': 46.77, 'FamousFor': 'Football'},
    'France': {'Capital': 'Paris', 'Population': 66.03, 'FamousFor': 'Eiffel Tower'},
    'Germany': {'Capital': 'Berlin', 'Population': 80.62, 'FamousFor': 'Cars'},
    'Norway': {'Capital': 'Oslo', 'Population': 5.084, 'FamousFor': 'Midnight sun'}
}

# Converting the dictionary to a DataFrame
df = pd.DataFrame.from_dict(europe_dict, orient='index')

# Checking the dimension/shape of the DataFrame
print("Shape of the DataFrame:", df.shape)

# Checking the data types of the columns
print("Data types of the columns:")
print(df.dtypes)


Shape of the DataFrame: (4, 3)
Data types of the columns:
Capital        object
Population    float64
FamousFor      object
dtype: object


15.Create a pandas series having values 4, 7, -5, 3, NAN and their index as d, b, a, c, e

  find the minimum of all values & the maximum of all value


In [ ]:
import pandas as pd
import numpy as np

# Creating the pandas Series
data = [4, 7, -5, 3, np.nan]
index = ['d', 'b', 'a', 'c', 'e']

series = pd.Series(data, index=index)

# Finding the minimum and maximum values, ignoring NaN
min_value = series.min()
max_value = series.max()
print("Pandas Series:")
print(series)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Pandas Series:
d    4.0
b    7.0
a   -5.0
c    3.0
e    NaN
dtype: float64

Minimum value: -5.0
Maximum value: 7.0


16. Using the series in question 15 sort:
the values in ascending order
the values in decending order


In [ ]:
import pandas as pd
import numpy as np

# Creating the pandas Series
data = [4, 7, -5, 3, np.nan]
index = ['d', 'b', 'a', 'c', 'e']

series = pd.Series(data, index=index)

# Sorting in ascending order (NaN will be placed at the end by default)
ascending_order = series.sort_values(ascending=True)

# Sorting in descending order (NaN will be placed at the end by default)
descending_order = series.sort_values(ascending=False)
print("Series in ascending order:")
print(ascending_order)

print("\nSeries in descending order:")
print(descending_order)


Series in ascending order:
a   -5.0
c    3.0
d    4.0
b    7.0
e    NaN
dtype: float64

Series in descending order:
b    7.0
d    4.0
c    3.0
a   -5.0
e    NaN
dtype: float64
